### ISSUE TITLE
Needs documentation on how to run the application

### ISSUE THREAD

**Issue by C-Duv** [amiroslaw/TimeFX#1]
_Disclaimer: I am not used to running Java applications so the issue is probably my fault, but in the end, a little documentation for neophytes could be interesting._

I tried to run 1.0 release (both native image and .jar) on Ubuntu 22 but it fails.

Executing the native image initially complained about "libfreetype.so" :

```Shell
$ ./timefx
./timefx: error while loading shared libraries: libfreetype.so: cannot open shared object file: No such file or directory
```

But after I installed `libfreetype6-dev` package it now complains about graphics device:

```Shell
$ ./timefx
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics@17.0.5/com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
	at javafx.graphics@17.0.5/com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
	at javafx.graphics@17.0.5/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:266)
	at javafx.graphics@17.0.5/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at javafx.graphics@17.0.5/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at javafx.graphics@17.0.5/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at javafx.graphics@17.0.5/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at javafx.graphics@17.0.5/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at javafx.graphics@17.0.5/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
	at javafx.graphics@17.0.5/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
	... 3 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
	at javafx.graphics@17.0.5/com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:278)
	at javafx.graphics@17.0.5/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
	at javafx.graphics@17.0.5/com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
	at javafx.graphics@17.0.5/com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
	at javafx.graphics@17.0.5/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
	at javafx.graphics@17.0.5/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

I have OpenJFX 11.0 and OpenJDK 11 JRE installed.

Also downloaded the javafx-sdk v19 and tried what's documented on https://openjfx.io/openjfx-docs/#install-javafx:

```Shell
$ java --module-path javafx-sdk-19/lib --add-modules javafx.controls  ./timefx
Error occurred during initialization of boot layer
java.lang.module.FindException: Module javafx.controls not found
```

**Comment by amiroslaw** [comment]
Thanks for the feedback.

I released two versions of the application:

- "timefx" - it's a native image - should work without Java. You can run it like a normal application.
- "TimeFX.jar" - it needs Java version 17 with the JavaFX runtime

Unfortunately, it seems that Ubuntu doesn't have some libraries for nativeimage. I'll have to test it and figure out what is missing and if I should bundle additional libraries.

Try to run TimeFX.jar. You need Java 17 (not 11) with the JavaFX. You have two options to run jar version:

Upgrading your Java JRE to 17 and adding a module from javafx-sdk, like in this tutorial https://openjfx.io/openjfx-docs/#install-javafx

    java --module-path javafx-sdk-19/lib --add-modules javafx.controls  -jar "path/to/TimeFX.jar"

If Ubuntu LTS doesn't have Java 17 in the repository, I think it'd be easiest to use Liberica JDK which includes JavaFX. [Installation guide](https://bell-sw.com/pages/liberica*install*guide-17.0.5/#apt-repository-deb-based-linux-distributions). After that, you run it like a normal Java
application.

    java -jar "path/to/TimeFX.jar"

IMPORTANT: Always make sure that your `$JAVA_HOME` and java version is correct.

Pleas reply if it worked and the pie chart has colors on your machine.

**Comment by C-Duv** [comment]
Thanks for the help.

I upgraded to Java 17 (`openjdk-17-jre` package).

Java version (`java --version`) now looks OK:

```
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu122.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu122.04, mixed mode, sharing)
```

But running the following command hangs (no window opens and the command does not return).

```Shell
export PATH_TO_FX=./javafx-sdk-19/lib
export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
java --module-path $PATH_TO_FX --add-modules javafx.controls -jar ./TimeFX.jar
```

If relevant: I am running X11 (not Wayland).

**Comment by amiroslaw** [comment]
I've done some tests on the lubuntu lts. I don't have a solution for nativeimage package, this technology isn't mature.

It seems that you run the jar correctly, but you don't have any data from timewarrior. They should be in the `~/.timewarrior/data/` folder, also you can check if they are correct by command:

	timew export :all

I found one additional bug. 😅 All tasks have to have end data, so they have to be stopped before you want to run my program. 

Apparently, you don't need to have the newest openjfx - java 17 and openjfx 11 from ubuntu's repository are fine. With that requirements you can start the app like this:

	java --module-path /usr/share/openjfx/lib --add-modules javafx.controls -jar ~/TimeFX.jar

I'll try to fix those issues soon.

**Comment by C-Duv** [comment]
Issue seems to persist, I tried with the JDK installed (and not only the JRE) and i also hangs.

I will try on a Ubuntu fresh install to see if my setup is not the cause of all of this.

If it can help, here is a `strace` obtained with the following command:

`LC_ALL=en strace java --module-path /usr/share/openjfx/lib --add-modules javafx.controls -jar ./TimeFX.jar`

```
execve("/usr/bin/java", ["java", "--module-path", "/usr/share/openjfx/lib", "--add-modules", "javafx.controls", "-jar", "./TimeFX.jar"], 0x7ffca8891ad0 /* 58 vars */) = 0
brk(NULL)                               = 0x56464dcec000
arch_prctl(0x3001 /* ARCH_??? */, 0x7fff4c07cce0) = -1 EINVAL (Invalid argument)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fadfb785000
readlink("/proc/self/exe", "/usr/lib/jvm/java-19-openjdk-amd"..., 4096) = 43
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/glibc-hwcaps/x86-64-v3/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/glibc-hwcaps/x86-64-v3", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/glibc-hwcaps/x86-64-v2/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/glibc-hwcaps/x86-64-v2", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/tls/x86_64/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/tls/x86_64/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/tls/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/tls/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/tls/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/tls/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/tls/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/tls", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/x86_64/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/x86_64/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin", {st_mode=S_IFDIR|0755, st_size=4096, ...}, 0) = 0
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/glibc-hwcaps/x86-64-v3/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/glibc-hwcaps/x86-64-v3", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/glibc-hwcaps/x86-64-v2/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/glibc-hwcaps/x86-64-v2", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/tls/x86_64/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/tls/x86_64/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/tls/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/tls/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/tls/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/tls/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/tls/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/tls", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/x86_64/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/x86_64/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/x86_64/libjli.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/x86_64", 0x7fff4c07bf00, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/libjli.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=63576, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 65840, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fadfb774000
mmap(0x7fadfb776000, 40960, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fadfb776000
mmap(0x7fadfb780000, 12288, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xc000) = 0x7fadfb780000
mmap(0x7fadfb783000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe000) = 0x7fadfb783000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/libc.so.6", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=111987, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 111987, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fadfb758000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\237\2\0\0\0\0\0"..., 832) = 832
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
pread64(3, "\4\0\0\0 \0\0\0\5\0\0\0GNU\0\2\0\0\300\4\0\0\0\3\0\0\0\0\0\0\0"..., 48, 848) = 48
pread64(3, "\4\0\0\0\24\0\0\0\3\0\0\0GNU\0i8\235HZ\227\223\333\350s\360\352,\223\340."..., 68, 896) = 68
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2216304, ...}, AT_EMPTY_PATH) = 0
pread64(3, "\6\0\0\0\4\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0@\0\0\0\0\0\0\0"..., 784, 64) = 784
mmap(NULL, 2260560, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fadfb530000
mmap(0x7fadfb558000, 1658880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28000) = 0x7fadfb558000
mmap(0x7fadfb6ed000, 360448, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bd000) = 0x7fadfb6ed000
mmap(0x7fadfb745000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x214000) = 0x7fadfb745000
mmap(0x7fadfb74b000, 52816, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fadfb74b000
close(3)                                = 0
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/bin/../lib/libz.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=108936, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 110776, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fadfb514000
mprotect(0x7fadfb516000, 98304, PROT_NONE) = 0
mmap(0x7fadfb516000, 69632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7fadfb516000
mmap(0x7fadfb527000, 24576, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x13000) = 0x7fadfb527000
mmap(0x7fadfb52e000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x19000) = 0x7fadfb52e000
close(3)                                = 0
mmap(NULL, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fadfb511000
arch_prctl(ARCH_SET_FS, 0x7fadfb511740) = 0
set_tid_address(0x7fadfb511a10)         = 24514
set_robust_list(0x7fadfb511a20, 24)     = 0
rseq(0x7fadfb5120e0, 0x20, 0, 0x53053053) = 0
mprotect(0x7fadfb745000, 16384, PROT_READ) = 0
mprotect(0x7fadfb52e000, 4096, PROT_READ) = 0
mprotect(0x7fadfb783000, 4096, PROT_READ) = 0
mprotect(0x56464d6af000, 4096, PROT_READ) = 0
mprotect(0x7fadfb7bf000, 8192, PROT_READ) = 0
prlimit64(0, RLIMIT_STACK, NULL, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
munmap(0x7fadfb758000, 111987)          = 0
getrandom("\xdf\xb1\x1d\x01\x32\x6a\x0e\xb0", 8, GRND_NONBLOCK) = 8
brk(NULL)                               = 0x56464dcec000
brk(0x56464dd0d000)                     = 0x56464dd0d000
openat(AT_FDCWD, "./TimeFX.jar", O_RDONLY) = 3
mmap(NULL, 200704, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fadfb4e0000
lseek(3, -22, SEEK_END)                 = 10435030
read(3, "PK\5\6\0\0\0\0\327\31\327\31\270\257\t\0\36\212\225\0\0\0", 22) = 22
lseek(3, 9800222, SEEK_SET)             = 9800222
read(3, "PK\1\2\24\0\24\0\10\10\10\0\10\266\211U\223S\273\334A\0\0\0A\0\0\0\24\0\4\0"..., 46) = 46
lseek(3, 0, SEEK_SET)                   = 0
read(3, "PK\3\4\24\0\10\10\10\0\10\266\211U\0\0\0\0\0\0\0\0\0\0\0\0\24\0\4\0", 30) = 30
lseek(3, 9800222, SEEK_SET)             = 9800222
read(3, "PK\1\2\24\0\24\0\10\10\10\0\10\266\211U\223S\273\334A\0\0\0A\0\0\0\24\0\4\0"..., 1024) = 1024
lseek(3, 0, SEEK_SET)                   = 0
read(3, "PK\3\4\24\0\10\10\10\0\10\266\211U\0\0\0\0\0\0\0\0\0\0\0\0\24\0\4\0", 30) = 30
munmap(0x7fadfb4e0000, 200704)          = 0
lseek(3, 54, SEEK_SET)                  = 54
read(3, "\363M\314\313LK-.\321\rK-*\316\314\317\263R0\3243\340\345\362M\314\314\323u\316I,"..., 65) = 65
close(3)                                = 0
readlink("/proc/self/exe", "/usr/lib/jvm/java-19-openjdk-amd"..., 4096) = 43
access("/usr/lib/jvm/java-19-openjdk-amd64/lib/libjava.so", F_OK) = 0
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/lib/jvm.cfg", O_RDONLY) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=54, ...}, AT_EMPTY_PATH) = 0
read(3, "-server KNOWN\n-client IGNORE\n-ze"..., 4096) = 54
read(3, "", 4096)                       = 0
close(3)                                = 0
newfstatat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/lib/server/libjvm.so", {st_mode=S_IFREG|0644, st_size=20884728, ...}, 0) = 0
openat(AT_FDCWD, "/usr/lib/jvm/java-19-openjdk-amd64/lib/server/libjvm.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=20884728, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 21264880, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fadfa0c9000
mprotect(0x7fadfa356000, 17158144, PROT_NONE) = 0
mmap(0x7fadfa356000, 14368768, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x28d000) = 0x7fadfa356000
mmap(0x7fadfb10a000, 2785280, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1041000) = 0x7fadfb10a000
mmap(0x7fadfb3b3000, 1056768, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x12e9000) = 0x7fadfb3b3000
mmap(0x7fadfb4b5000, 375280, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fadfb4b5000
close(3)                                = 0
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=111987, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 111987, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7fadfb758000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libstdc++.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=2252096, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 2267328, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fadf9e9f000
mmap(0x7fadf9f39000, 1114112, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x9a000) = 0x7fadf9f39000
mmap(0x7fadfa049000, 454656, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1aa000) = 0x7fadfa049000
mmap(0x7fadfa0b8000, 57344, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x218000) = 0x7fadfa0b8000
mmap(0x7fadfa0c6000, 10432, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7fadfa0c6000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libm.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=940560, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 942344, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fadf9db8000
mmap(0x7fadf9dc6000, 507904, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe000) = 0x7fadf9dc6000
mmap(0x7fadf9e42000, 372736, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x8a000) = 0x7fadf9e42000
mmap(0x7fadf9e9d000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0xe4000) = 0x7fadf9e9d000
close(3)                                = 0
openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libgcc_s.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
newfstatat(3, "", {st_mode=S_IFREG|0644, st_size=125488, ...}, AT_EMPTY_PATH) = 0
mmap(NULL, 127720, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7fadf9d98000
mmap(0x7fadf9d9b000, 94208, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x3000) = 0x7fadf9d9b000
mmap(0x7fadf9db2000, 16384, PROT_READ, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1a000) = 0x7fadf9db2000
mmap(0x7fadf9db6000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1d000) = 0x7fadf9db6000
close(3)                                = 0
mprotect(0x7fadf9db6000, 4096, PROT_READ) = 0
mprotect(0x7fadf9e9d000, 4096, PROT_READ) = 0
mprotect(0x7fadfa0b8000, 45056, PROT_READ) = 0
mprotect(0x7fadfb3b3000, 835584, PROT_READ) = 0
brk(0x56464dd33000)                     = 0x56464dd33000
getpid()                                = 24514
munmap(0x7fadfb758000, 111987)          = 0
rt_sigaction(SIGRT_1, {sa_handler=0x7fadfb5c18f0, sa_mask=[], sa_flags=SA_RESTORER|SA_ONSTACK|SA_RESTART|SA_SIGINFO, sa_restorer=0x7fadfb572520}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
mmap(NULL, 1048576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_STACK, -1, 0) = 0x7fadf9c98000
rt_sigprocmask(SIG_BLOCK, ~[], [], 8)   = 0
clone3({flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID, child_tid=0x7fadf9d97910, parent_tid=0x7fadf9d97910, exit_signal=0, stack=0x7fadf9c98000, stack_size=0xfef00, tls=0x7fadf9d97640} => {parent_tid=[24515]}, 88) = 24515
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
futex(0x7fadf9d97910, FUTEX_WAIT_BITSET|FUTEX_CLOCK_REALTIME, 24515, NULL, FUTEX_BITSET_MATCH_ANYError: An unexpected error occurred while trying to open file ./TimeFX.jar
) = ?
+++ exited with 1 +++
```
(It exits by itself, I don't press [Ctrl]+[C])

**Comment by amiroslaw** [comment]
Sorry for my delay. 
Are you sure that your config folder with data is correct? I can reproduce that behavior only when timewarrior can't detect configuration folder (`~/.timewarrior/data/`).

What output do you have with this command?

> timew export
